version: "3"
services:
  # postgres:
  #   image: postgres
  #   mem_limit: 128m
  #   environment:
  #     POSTGRES_PASSWORD: strong_password@9841
  # redis:
  #   mem_limit: 128m
  #   image: 'redis:alpine'
  client:
    image: "walosha/multi-client"
    # mem_limit: 128m
    hostname: client
  api:
    image: "walosha/multi-server"
    # mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=strong_password@9841
      - PGPORT=5432
  worker:
    image: "walosha/multi-worker"
    # mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    image: "walosha/multi-nginx"
    # mem_limit: 256m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client
