apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - ./k8s/*
build:
  artifacts:
    - image: walosha/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
    - image: walosha/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: walosha/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
