name: multi-container
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t walosha/multi-client -f ./client/Dockerfile.dev ./client
      - run: docker build -t walosha/multi-nginx -f ./nginx/Dockerfile.dev ./nginx
      - run: docker build -t walosha/multi-server -f ./server/Dockerfile.dev ./server
      - run: docker build -t walosha/multi-worker -f ./worker/Dockerfile.dev ./worker
      - run: docker push walosha/multi-client
      - run: docker push walosha/multi-nginx
      - run: docker push walosha/multi-server
      - run: docker push walosha/multi-worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: application
          environment_name: Application-env
          existing_bucket_name: elasticbeanstalk-us-east-1-542138831145
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: docker-compose.yml
