name: multi-container
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Docker HUb
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t walosha/multi-client -f ./client/Dockerfile ./client
          docker build -t walosha/multi-nginx -f ./nginx/Dockerfile ./nginx
          docker build -t walosha/multi-server -f ./server/Dockerfile ./server
          docker build -t walosha/multi-worker -f ./worker/Dockerfile ./worker
          docker push walosha/multi-client
          docker push walosha/multi-nginx
          docker push walosha/multi-server
          docker push walosha/multi-worker

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: "v1.24.0"
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name k8s-tutorial --region us-east-1

      - name: Deploy to EKS
        run: bash ./deploy.sh
